import '../utils/accounting_math.dart';

class AccountingAccount {
  AccountingAccount({required this.id, required this.code, required this.name, required this.type, required this.normalBalance, this.parentId, this.parentName, this.description, this.allowManualPosting = true, this.active = true, this.systemAccount = false, this.depth = 0});
  final String id, code, name, type, normalBalance; final String? parentId, parentName, description; final bool allowManualPosting, active, systemAccount; final int depth;
  factory AccountingAccount.fromJson(Map<String,dynamic> j)=>AccountingAccount(id:(j['id']??j['account_id']??j['code']).toString(),code:(j['code']??j['account_code']??'').toString(),name:(j['name']??j['account_name']??'').toString(),type:(j['type']??j['account_type']??'').toString(),normalBalance:(j['normal_balance']??j['normalBalance']??'').toString(),parentId:j['parent_id']?.toString(),parentName:j['parent_name']?.toString(),description:j['description']?.toString(),allowManualPosting:j['allow_manual_posting']??j['posting_allowed']??j['allowManualPosting']??true,active:j['active']??j['is_active']??true,systemAccount:j['system_account']??j['is_system']??false,depth:int.tryParse((j['depth']??j['level']??0).toString())??0);
}

class JournalLineDraft { String? accountId, description, customerId, loanId; String debit, credit; JournalLineDraft({this.accountId,this.description,this.customerId,this.loanId,this.debit='',this.credit=''}); bool get hasDebit=>toCents(debit)>0; bool get hasCredit=>toCents(credit)>0; bool get isValid=>accountId!=null && accountId!.isNotEmpty && (hasDebit!=hasCredit); Map<String,dynamic> toJson()=>{'account_id':accountId,'description':description,'customer_id':customerId,'loan_id':loanId,'debit':debit.isEmpty?'0.00':debit,'credit':credit.isEmpty?'0.00':credit}; }

class JournalEntry { JournalEntry({required this.id, required this.journalNo, this.date, this.description, this.referenceType, this.referenceId, this.sourceModule, this.status='DRAFT', this.totalDebit='0', this.totalCredit='0', this.createdBy, this.postedBy, this.postedAt, this.reversalReference, this.lines=const []});
  final String id,journalNo,status,totalDebit,totalCredit; final String? date,description,referenceType,referenceId,sourceModule,createdBy,postedBy,postedAt,reversalReference; final List<JournalLine> lines;
  factory JournalEntry.fromJson(Map<String,dynamic> j)=>JournalEntry(id:(j['id']??j['journal_id']??'').toString(),journalNo:(j['journal_no']??j['journalNo']??j['number']??j['id']??'').toString(),date:j['date']?.toString()??j['journal_date']?.toString(),description:j['description']?.toString(),referenceType:j['reference_type']?.toString(),referenceId:j['reference_id']?.toString(),sourceModule:j['source_module']?.toString(),status:(j['status']??'DRAFT').toString(),totalDebit:(j['total_debit']??j['totalDebit']??0).toString(),totalCredit:(j['total_credit']??j['totalCredit']??0).toString(),createdBy:j['created_by']?.toString(),postedBy:j['posted_by']?.toString(),postedAt:j['posted_at']?.toString(),reversalReference:j['reversal_reference']?.toString()??j['reversal_journal_no']?.toString(),lines:((j['lines']??[]) as List).whereType<Map<String,dynamic>>().map(JournalLine.fromJson).toList()); }
class JournalLine { JournalLine({required this.lineNo,this.accountCode,this.accountName,this.description,this.customer,this.loan,this.debit='0',this.credit='0'}); final int lineNo; final String? accountCode,accountName,description,customer,loan; final String debit,credit; factory JournalLine.fromJson(Map<String,dynamic> j)=>JournalLine(lineNo:int.tryParse((j['line_no']??j['lineNo']??1).toString())??1,accountCode:j['account_code']?.toString(),accountName:j['account_name']?.toString(),description:j['description']?.toString(),customer:j['customer']?.toString()??j['customer_id']?.toString(),loan:j['loan']?.toString()??j['loan_id']?.toString(),debit:(j['debit']??0).toString(),credit:(j['credit']??0).toString()); }
